[package]
name = "css_typegen"
version = "0.1.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.5"
syn = "1.0.5"
quote = "1.0.2"
regex = "1.3.1"
