[package]
name = "css_typegen"
version = "0.2.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1"
syn = "1"
quote = "1"
regex = "1"
